apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # Just need this line to work in cloud
spec:
  rules:
    - host: {{ .Values.appHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.serviceName }}
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: 80
    - host: jenkins.{{ .Values.appHost }}
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Values.jenkins.serviceName }}
                  port:
                    number: 80
