apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
spec:
  selector:
    app: {{ .Values.frontend.label }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.label }}
    spec:
      containers:
        - name: react-container
          image: "vitalisnitko/react:{{ .Values.frontend.imageTag }}"
          ports:
            - containerPort: 80
