apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.serviceName }}
spec:
  selector:
    app: {{ .Values.db.label }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.db.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.label }}
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.3.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: {{ .Values.db.initialDb }}
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "0.75Gi"
          volumeMounts:
            - name: {{ .Values.db.volumeName }}
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ .Values.db.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.claimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
