version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 3s
      timeout: 20s
      retries: 20

  backend:
    container_name: backend
    image: ${BACKEND_IMAGE}
    build:
      context: ./spring-oauth2
      dockerfile: ${DOCKERFILE:-Dockerfile-local}
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - REMOTE_HOST=${REMOTE_HOST}

  frontend:
    container_name: frontend
    image: ${FRONTEND_IMAGE}
    build: ./react-oauth2
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
