version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 3s
      timeout: 20s
      retries: 20
      
  s3:
    image: scireum/s3-ninja
    container_name: s3
    ports:
      - "9444:9000"
    volumes:
      - /home/sirius/data:/root/.s3ninja

  backend:
    container_name: backend
    build: ./spring-oauth2
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_SERVICE_NAME=mysql
      - DB_SERVICE_PORT=3306
      - S3_SERVICE_NAME=host.docker.internal
      - S3_SERVICE_PORT=9444
      - CLIENT_PORT=
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USERNAME=${EMAIL_USERNAME}

  frontend:
    container_name: frontend
    build:
      context: ./react-justchatting
    ports:
      - "80:80"

volumes:
  db_data:
