pipeline {
	agent any

	environment {
		DOCKER_TAG = "1.0.${BUILD_NUMBER}"
		SSH_USER = 'wo4ko'
		REMOTE_HOST = '89.169.169.180'
	}

	stages {
		stage('Set env variables') {
			steps {
				script {
					withCredentials([
						usernamePassword(credentialsId: 'docker-credentials', passwordVariable: 'DOCKER_CREDS_PSW', usernameVariable: 'DOCKER_USERNAME'),
					]) {
						env.VITE_IMAGE = "${DOCKER_USERNAME}/vite:${DOCKER_TAG}"
					}
				}
			}
		}
		stage('Checkout') {
			steps {
				git branch: 'just-chatting-global', url: 'https://github.com/vsnitko/oauth2.git'
			}
		}
		stage('Build Vite') {
			steps {
				dir('react-justchatting') {
					script {
						sh 'npm install'
						sh 'CI=false npm run build'
					}
				}
			}
		}
		stage('Build docker-compose') {
			steps {
			    dir('react-justchatting') {
				    script {
				    	sh "docker-compose build"
				    }
				}
			}
		}
		stage('Push docker-compose to DockerHub') {
			steps {
			    dir('react-justchatting') {
				    script {
				    	withCredentials([usernamePassword(credentialsId: 'docker-credentials', passwordVariable: 'DOCKER_CREDS_PSW', usernameVariable: 'DOCKER_CREDS_USR')]) {
				    		sh 'echo $DOCKER_CREDS_PSW | docker login --username $DOCKER_CREDS_USR --password-stdin'
				    		sh "docker-compose push"
				    	}
				    }
				}
			}
		}
		stage('Pull docker-compose and Restart Containers in Cloud') {
			steps {
			    dir('react-justchatting') {
			    	script {
			    		sshagent(['ssh']) {
			    			withCredentials([usernamePassword(credentialsId: 'docker-credentials', passwordVariable: 'DOCKER_CREDS_PSW', usernameVariable: 'DOCKER_CREDS_USR')]){
			    				sh "scp docker-compose.yml ${SSH_USER}@${REMOTE_HOST}:/opt/oauth2/"

			    				def variables = [
			    					"VITE_IMAGE=${VITE_IMAGE}"
			    				]
			    				for (variable in variables) {
			    					def (key, value) = variable.split('=')
			    					sh """ssh -o StrictHostKeyChecking=no ${SSH_USER}@${REMOTE_HOST} '
			    					if grep -q "^${key}=" /etc/environment; then
    		    					    sudo sed -i "s|^${key}=.*|${variable}|" /etc/environment
    		    					else
    		    					    echo "${variable}" | sudo tee -a /etc/environment
    		    					fi
			    					'"""
			    				}

			    				sh """ssh ${SSH_USER}@${REMOTE_HOST} '
			    				source /etc/environment
			    				echo ${DOCKER_CREDS_PSW} | docker login --username ${DOCKER_CREDS_USR} --password-stdin
			    				cd /opt/oauth2
			    				mkdir -p react-justchatting
			    				docker-compose pull
			    				docker-compose up -d --no-build
			    				'"""
			    			}
			    		}
			    	}
				}
			}
		}
	}
}
